### ISSUE TITLE
ruboty 対応

### ISSUE THREAD

**Issue by tily** [tily/domoraen#3]
* リプライを受けたときの形態素解析の方法を MeCab 以外にする必要がある
  * Yahoo! API でよさそう

**Comment by tily** [comment]
```
2015-03-31T22:26:54.395268+00:00 heroku[bot.1]: Starting process with command `bundle exec ruboty -l bin/domoraen-ruboty`
2015-03-31T22:26:55.030209+00:00 heroku[bot.1]: State changed from starting to up
2015-03-31T22:26:58.839626+00:00 app[bot.1]: /app/lib/domoraen.rb:6: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
2015-03-31T23:12:32.976184+00:00 app[bot.1]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:122:in `sysread': end of file reached (EOFError)
2015-03-31T23:12:32.976191+00:00 app[bot.1]:    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:122:in `readpartial'
2015-03-31T23:12:32.976207+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/commands/run.rb:5:in `call'
2015-03-31T23:12:32.976213+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/ruboty:23:in `<main>'
2015-03-31T23:12:32.976202+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-twitter-0.0.8/lib/ruboty/adapters/twitter.rb:34:in `listen'
2015-03-31T23:12:32.976203+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-twitter-0.0.8/lib/ruboty/adapters/twitter.rb:19:in `run'
2015-03-31T23:12:32.976212+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/ruboty:23:in `load'
2015-03-31T23:12:32.976193+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:21:in `stream'
2015-03-31T23:12:32.976206+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:22:in `run'
2015-03-31T23:12:32.976200+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:91:in `user'
2015-03-31T23:12:32.976204+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:54:in `adapt'
2015-03-31T23:12:32.976199+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:118:in `request'
2015-03-31T23:12:32.976208+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/bin/ruboty:6:in `<top (required)>'
2015-03-31T23:12:33.937958+00:00 heroku[bot.1]: State changed from crashed to starting
2015-03-31T23:12:33.920928+00:00 heroku[bot.1]: Process exited with status 1
2015-03-31T23:12:33.937321+00:00 heroku[bot.1]: State changed from up to crashed
2015-03-31T23:12:36.327248+00:00 heroku[bot.1]: Starting process with command `bundle exec ruboty -l bin/domoraen-ruboty`
2015-03-31T23:12:37.058531+00:00 heroku[bot.1]: State changed from starting to up
2015-03-31T23:12:39.388895+00:00 app[bot.1]: /app/lib/domoraen.rb:6: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
2015-03-31T23:19:46.011201+00:00 app[bot.1]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:122:in `sysread': end of file reached (EOFError)
2015-03-31T23:19:46.011209+00:00 app[bot.1]:    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:122:in `readpartial'
2015-03-31T23:19:46.011213+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:91:in `user'
2015-03-31T23:19:46.011211+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:21:in `stream'
2015-03-31T23:19:46.011212+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:118:in `request'
2015-03-31T23:19:46.011227+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-twitter-0.0.8/lib/ruboty/adapters/twitter.rb:19:in `run'
2015-03-31T23:19:46.011230+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:54:in `adapt'
2015-03-31T23:19:46.011232+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/robot.rb:22:in `run'
2015-03-31T23:19:46.011235+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/lib/ruboty/commands/run.rb:5:in `call'
2015-03-31T23:19:46.011236+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-1.2.1/bin/ruboty:6:in `<top (required)>'
2015-03-31T23:19:46.011216+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/ruboty-twitter-0.0.8/lib/ruboty/adapters/twitter.rb:34:in `listen'
2015-03-31T23:19:46.011239+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/ruboty:23:in `load'
2015-03-31T23:19:46.011242+00:00 app[bot.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/ruboty:23:in `<main>'
2015-03-31T23:19:51.771738+00:00 heroku[bot.1]: State changed from up to crashed
2015-03-31T23:19:51.733402+00:00 heroku[bot.1]: Process exited with status 1
```
